spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_prueba_tec
    username: postgres
    password: ecuacion
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true